create table user_profile (
    id bigint generated by default as identity primary key,
    user_code varchar(64) not null,
    goal varchar(32) not null,
    daily_minutes int not null,
    study_start_time varchar(5),
    review_time varchar(5),
    status varchar(16) not null default 'ACTIVE',
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_user_profile_user_code unique (user_code),
    constraint chk_user_profile_daily_minutes check (daily_minutes between 5 and 180)
);
