-- Expand user_profile with level and preference fields
alter table user_profile add column sub_goals varchar(1024) not null default '[]';
alter table user_profile add column overall_level varchar(16);
alter table user_profile add column vocab_level varchar(16);
alter table user_profile add column grammar_level varchar(16);
alter table user_profile add column reading_level varchar(16);
alter table user_profile add column output_level varchar(16);
alter table user_profile add column preferred_modes varchar(1024) not null default '[]';
alter table user_profile add column motivation_style varchar(32);
alter table user_profile add column fatigue_tolerance varchar(32);

-- learning_item: content pool
create table learning_item (
    id bigint generated by default as identity primary key,
    item_code varchar(64) not null,
    type varchar(32) not null,
    content varchar(255) not null,
    meaning_zh varchar(255) not null,
    difficulty int not null,
    theme varchar(64) not null,
    tags varchar(2048) not null default '[]',
    examples varchar(4096) not null default '[]',
    related_item_codes varchar(2048) not null default '[]',
    status varchar(16) not null default 'ACTIVE',
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_learning_item_item_code unique (item_code),
    constraint chk_learning_item_difficulty check (difficulty between 1 and 10)
);

create index idx_learning_item_type on learning_item(type);
create index idx_learning_item_theme on learning_item(theme);
create index idx_learning_item_difficulty on learning_item(difficulty);

-- mastery_state: user's long-term mastery per item
create table mastery_state (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    learning_item_id bigint not null,
    seen_count int not null default 0,
    correct_count int not null default 0,
    wrong_count int not null default 0,
    correct_streak int not null default 0,
    recognition_score numeric(5,2) not null default 0,
    recall_score numeric(5,2) not null default 0,
    output_score numeric(5,2) not null default 0,
    memory_strength numeric(5,2) not null default 0,
    forget_risk numeric(5,2) not null default 0,
    last_seen_at timestamp,
    next_review_at timestamp,
    last_mode varchar(32),
    recommended_mode varchar(32),
    status varchar(32) not null default 'NEW',
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_mastery_state_user_item unique (user_id, learning_item_id)
);

create index idx_mastery_state_user_next_review on mastery_state(user_id, next_review_at);
create index idx_mastery_state_user_status on mastery_state(user_id, status);

-- study_session: one learning session record
create table study_session (
    id bigint generated by default as identity primary key,
    session_code varchar(64) not null,
    user_id bigint not null,
    session_date date not null,
    session_type varchar(32) not null,
    status varchar(16) not null default 'STARTED',
    duration_min int,
    new_items_count int not null default 0,
    review_items_count int not null default 0,
    accuracy numeric(5,2),
    completion_rate numeric(5,2),
    fatigue_feedback varchar(32),
    mood_feedback varchar(32),
    focus_theme varchar(64),
    started_at timestamp not null default current_timestamp,
    completed_at timestamp,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_study_session_session_code unique (session_code)
);

create index idx_study_session_user_date on study_session(user_id, session_date);
create index idx_study_session_user_type on study_session(user_id, session_type);

-- attempt_log: single attempt within a session
create table attempt_log (
    id bigint generated by default as identity primary key,
    attempt_code varchar(64) not null,
    user_id bigint not null,
    learning_item_id bigint not null,
    study_session_id bigint not null,
    mode varchar(32) not null,
    result varchar(16) not null,
    response_text text,
    response_time_ms int,
    hint_used boolean not null default false,
    error_type varchar(32),
    error_details varchar(2048),
    occurred_at timestamp not null default current_timestamp,
    llm_explanation_snapshot text,
    created_at timestamp not null default current_timestamp,
    constraint uk_attempt_log_attempt_code unique (attempt_code)
);

create index idx_attempt_log_user_item on attempt_log(user_id, learning_item_id);
create index idx_attempt_log_session on attempt_log(study_session_id);
create index idx_attempt_log_error_type on attempt_log(error_type);
