-- daily_plan_snapshot: daily plan header
create table daily_plan_snapshot (
    id bigint generated by default as identity primary key,
    plan_code varchar(64) not null,
    user_id bigint not null,
    plan_date date not null,
    plan_type varchar(32) not null,
    status varchar(16) not null default 'GENERATED',
    total_new_count int not null default 0,
    total_review_count int not null default 0,
    total_output_count int not null default 0,
    load_reason varchar(2048) not null default '{}',
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_daily_plan_snapshot_plan_code unique (plan_code),
    constraint uk_daily_plan_snapshot_user_date_type unique (user_id, plan_date, plan_type)
);

-- daily_plan_item: items within a daily plan
create table daily_plan_item (
    id bigint generated by default as identity primary key,
    daily_plan_snapshot_id bigint not null,
    learning_item_id bigint not null,
    item_role varchar(32) not null,
    sequence_no int not null,
    selection_reason varchar(2048) not null default '{}',
    priority_score numeric(8,4),
    recommended_mode varchar(32),
    created_at timestamp not null default current_timestamp
);

create index idx_daily_plan_item_plan_sequence on daily_plan_item(daily_plan_snapshot_id, sequence_no);
create index idx_daily_plan_item_learning_item on daily_plan_item(learning_item_id);

-- weekly_review_snapshot: weekly review result
create table weekly_review_snapshot (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    week_start_date date not null,
    week_end_date date not null,
    completion_rate numeric(5,2) not null default 0,
    study_minutes int not null default 0,
    new_items_count int not null default 0,
    review_items_count int not null default 0,
    high_frequency_error_types varchar(1024) not null default '[]',
    strongest_themes varchar(1024) not null default '[]',
    weakest_themes varchar(1024) not null default '[]',
    next_week_suggestion varchar(2048) not null default '{}',
    created_at timestamp not null default current_timestamp,
    constraint uk_weekly_review_snapshot_user_week unique (user_id, week_start_date, week_end_date)
);
