create table error_pattern (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    pattern_key varchar(128) not null,
    label varchar(255) not null,
    description_zh varchar(2048),
    user_examples text not null default '[]',
    better_examples text not null default '[]',
    seen_count int not null default 1,
    severity varchar(32) not null default 'MEDIUM',
    status varchar(32) not null default 'ACTIVE',
    last_seen_at timestamp not null default current_timestamp,
    next_drill_at timestamp,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_error_pattern_user_pattern unique (user_id, pattern_key)
);

create index idx_error_pattern_user_status on error_pattern(user_id, status);
create index idx_error_pattern_user_next_drill on error_pattern(user_id, next_drill_at);

create table expression_gap (
    id bigint generated by default as identity primary key,
    user_id bigint not null,
    gap_key varchar(128) not null,
    zh_intent varchar(512) not null,
    natural_expressions text not null default '[]',
    user_attempts text not null default '[]',
    context varchar(128),
    seen_count int not null default 1,
    status varchar(32) not null default 'ACTIVE',
    last_seen_at timestamp not null default current_timestamp,
    next_drill_at timestamp,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_expression_gap_user_gap unique (user_id, gap_key)
);

create index idx_expression_gap_user_status on expression_gap(user_id, status);
create index idx_expression_gap_user_next_drill on expression_gap(user_id, next_drill_at);

create table coach_session (
    id bigint generated by default as identity primary key,
    session_code varchar(64) not null,
    user_id bigint not null,
    session_type varchar(32) not null,
    status varchar(32) not null default 'STARTED',
    summary text,
    detected_level_range varchar(32),
    started_at timestamp not null default current_timestamp,
    ended_at timestamp,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint uk_coach_session_code unique (session_code)
);

create index idx_coach_session_user_started on coach_session(user_id, started_at);

create table coach_turn (
    id bigint generated by default as identity primary key,
    coach_session_id bigint not null,
    mode varchar(32) not null,
    user_message text,
    coach_message text,
    detected_notes text not null default '[]',
    created_at timestamp not null default current_timestamp
);

create index idx_coach_turn_session_created on coach_turn(coach_session_id, created_at);
