#!/usr/bin/env python3
"""Generate Flyway migrations that enrich learning_item examples from Tatoeba."""

from __future__ import annotations

import argparse
import csv
import json
import re
import sys
import time
from collections import Counter, defaultdict
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable, Iterator


TOKEN_RE = re.compile(r"[a-zA-Z]+(?:[-'][a-zA-Z]+)*")
SEED_GLOB = "V[0-9]*__seed_vocabulary*.sql"
GENERATED_GLOB = "V*__enrich_examples_with_tatoeba_part*.sql"
GENERATED_HEADER = """-- Enrich learning_item examples with Tatoeba sentence pairs.
-- Source: Tatoeba Project, https://tatoeba.org/, CC BY 2.0 FR.
-- Generated by tools/enrich_examples.py from local tatoeba/sentences.csv and tatoeba/links.csv.

"""


@dataclass(frozen=True)
class ExampleCandidate:
    en: str
    zh: str
    sentence_id: int
    match_count: int


@dataclass
class TatoebaStats:
    english_retained: int = 0
    chinese_retained: int = 0
    english_with_zh: int = 0
    skipped_quality_filter: int = 0
    links_seen: int = 0
    translation_links: int = 0


@dataclass
class TatoebaIndex:
    english: dict[int, str]
    chinese: dict[int, str]
    en_to_zh: dict[int, list[int]]
    stats: TatoebaStats


@dataclass
class ValidationResult:
    files: int = 0
    update_statements: int = 0
    json_examples: int = 0


@dataclass
class UpdatePlan:
    updates: list[tuple[str, list[ExampleCandidate]]] = field(default_factory=list)
    json_examples: int = 0
    skipped_json_length: int = 0


class Progress:
    def __init__(self, enabled: bool = True, interval_seconds: float = 5.0) -> None:
        self.enabled = enabled
        self.interval_seconds = interval_seconds
        self.last = 0.0
        self.started = time.monotonic()

    def report(self, message: str, force: bool = False) -> None:
        if not self.enabled:
            return
        now = time.monotonic()
        if force or now - self.last >= self.interval_seconds:
            elapsed = now - self.started
            print(f"[{elapsed:7.1f}s] {message}", file=sys.stderr, flush=True)
            self.last = now


def normalize_content(text: str) -> str:
    text = text.strip().lower()
    return re.sub(r"\s+", " ", text)


def normalize_match_phrase(text: str) -> str:
    text = normalize_content(text)
    text = re.sub(r"\b(sb|sth)\.", r"\1", text)
    return text


def tokenize_sentence(text: str) -> list[str]:
    return [match.group(0).lower() for match in TOKEN_RE.finditer(text)]


def parse_seed_insert_rows(sql_text: str) -> Iterator[dict[str, str]]:
    lower_text = sql_text.lower()
    search_from = 0

    while True:
        insert_at = lower_text.find("insert into learning_item", search_from)
        if insert_at == -1:
            return

        columns_start = sql_text.find("(", insert_at)
        columns_end = sql_text.find(")", columns_start)
        if columns_start == -1 or columns_end == -1:
            raise ValueError("learning_item INSERT is missing a column list")

        columns = [column.strip().lower() for column in sql_text[columns_start + 1 : columns_end].split(",")]
        values_at = lower_text.find("values", columns_end)
        if values_at == -1:
            raise ValueError("learning_item INSERT is missing VALUES")

        statement_end = _find_statement_end(sql_text, values_at)
        yield from _parse_values_tuples(sql_text[values_at + len("values") : statement_end], columns)
        search_from = statement_end + 1


def _find_statement_end(sql_text: str, start: int) -> int:
    in_string = False
    i = start
    while i < len(sql_text):
        char = sql_text[i]
        if in_string:
            if char == "'":
                if i + 1 < len(sql_text) and sql_text[i + 1] == "'":
                    i += 2
                    continue
                in_string = False
        elif char == "'":
            in_string = True
        elif char == ";":
            return i
        i += 1
    return len(sql_text)


def _parse_values_tuples(values_text: str, columns: list[str]) -> Iterator[dict[str, str]]:
    i = 0
    while i < len(values_text):
        if values_text[i] != "(":
            i += 1
            continue

        i += 1
        fields: list[str] = []
        current: list[str] = []
        in_string = False

        while i < len(values_text):
            char = values_text[i]
            if in_string:
                if char == "'":
                    if i + 1 < len(values_text) and values_text[i + 1] == "'":
                        current.append("'")
                        i += 2
                        continue
                    in_string = False
                else:
                    current.append(char)
            else:
                if char == "'":
                    in_string = True
                elif char == ",":
                    fields.append("".join(current).strip())
                    current = []
                elif char == ")":
                    fields.append("".join(current).strip())
                    if len(fields) < len(columns):
                        raise ValueError(f"tuple has {len(fields)} fields, expected {len(columns)}")
                    yield dict(zip(columns, fields))
                    i += 1
                    break
                else:
                    current.append(char)
            i += 1
        else:
            raise ValueError("unterminated VALUES tuple")


def load_learning_items(migration_dir: Path) -> dict[str, list[str]]:
    content_to_codes: dict[str, list[str]] = defaultdict(list)
    for path in sorted(migration_dir.glob(SEED_GLOB), key=_flyway_sort_key):
        sql_text = path.read_text(encoding="utf-8")
        for row in parse_seed_insert_rows(sql_text):
            content = normalize_content(row.get("content", ""))
            item_code = row.get("item_code", "")
            if content and item_code:
                content_to_codes[content].append(item_code)
    return dict(content_to_codes)


def build_tatoeba_index(
    tatoeba_dir: Path,
    min_sentence_len: int = 12,
    max_sentence_len: int = 120,
    progress: Progress | None = None,
) -> TatoebaIndex:
    progress = progress or Progress(enabled=False)
    sentences_path = tatoeba_dir / "sentences.csv"
    links_path = tatoeba_dir / "links.csv"
    stats = TatoebaStats()
    english: dict[int, str] = {}
    chinese: dict[int, str] = {}

    with sentences_path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.reader(handle, delimiter="\t")
        for row_number, row in enumerate(reader, start=1):
            if len(row) < 3:
                continue
            try:
                sentence_id = int(row[0])
            except ValueError:
                continue
            lang = row[1]
            text = clean_sentence_text(row[2])
            if lang == "eng":
                if _is_quality_english(text, min_sentence_len, max_sentence_len):
                    english[sentence_id] = text
                    stats.english_retained += 1
                else:
                    stats.skipped_quality_filter += 1
            elif lang == "cmn":
                chinese[sentence_id] = text
                stats.chinese_retained += 1
            if row_number % 500_000 == 0:
                progress.report(
                    f"read {row_number:,} sentences; kept {stats.english_retained:,} English and {stats.chinese_retained:,} Chinese",
                    force=True,
                )

    en_to_zh: dict[int, list[int]] = defaultdict(list)
    with links_path.open("r", encoding="utf-8", newline="") as handle:
        reader = csv.reader(handle, delimiter="\t")
        for row_number, row in enumerate(reader, start=1):
            if len(row) < 2:
                continue
            try:
                left = int(row[0])
                right = int(row[1])
            except ValueError:
                continue
            stats.links_seen += 1
            if left in english and right in chinese:
                en_to_zh[left].append(right)
                stats.translation_links += 1
            elif right in english and left in chinese:
                en_to_zh[right].append(left)
                stats.translation_links += 1
            if row_number % 1_000_000 == 0:
                progress.report(
                    f"read {row_number:,} links; found {stats.translation_links:,} retained English-Chinese links",
                    force=True,
                )

    stats.english_with_zh = len(en_to_zh)
    progress.report(
        f"Tatoeba index ready: {stats.english_retained:,} English, {stats.chinese_retained:,} Chinese, {stats.english_with_zh:,} English with Chinese translations",
        force=True,
    )
    return TatoebaIndex(english=english, chinese=chinese, en_to_zh=dict(en_to_zh), stats=stats)


def clean_sentence_text(text: str) -> str:
    return re.sub(r"[\r\n]+", " ", text).strip()


def _is_quality_english(text: str, min_sentence_len: int, max_sentence_len: int) -> bool:
    if not (min_sentence_len <= len(text) <= max_sentence_len):
        return False
    if not text.isascii() or not all(char.isprintable() or char.isspace() for char in text):
        return False
    return any(char.isalpha() for char in text)


def match_examples(
    content_to_codes: dict[str, list[str]],
    index: TatoebaIndex,
    max_examples: int = 3,
    allow_missing_zh: bool = False,
    progress: Progress | None = None,
) -> tuple[dict[str, list[ExampleCandidate]], Counter]:
    progress = progress or Progress(enabled=False)
    stats: Counter = Counter()
    single_targets: dict[str, list[str]] = defaultdict(list)
    phrase_targets: dict[tuple[str, ...], list[str]] = defaultdict(list)
    max_phrase_len = 1

    for content in content_to_codes:
        phrase = normalize_match_phrase(content)
        if "..." in phrase:
            stats["template_phrase"] += 1
            continue
        tokens = tokenize_sentence(phrase)
        if not tokens:
            continue
        if len(tokens) == 1:
            single_targets[tokens[0]].append(content)
        elif len(tokens) <= 8:
            token_tuple = tuple(tokens)
            phrase_targets[token_tuple].append(content)
            max_phrase_len = max(max_phrase_len, len(tokens))

    candidates: dict[str, list[ExampleCandidate]] = defaultdict(list)
    seen_english: dict[str, set[str]] = defaultdict(set)
    sorted_english = sorted(index.english.items(), key=lambda item: len(item[1]))

    for position, (sentence_id, english_text) in enumerate(sorted_english, start=1):
        if position % 100_000 == 0:
            matched_items = sum(1 for examples in candidates.values() if examples)
            progress.report(
                f"matched {position:,}/{len(sorted_english):,} retained English sentences; {matched_items:,} content keys have candidates",
                force=True,
            )
        zh_ids = index.en_to_zh.get(sentence_id, [])
        if not zh_ids and not allow_missing_zh:
            stats["no_translation"] += 1
            continue
        zh_text = index.chinese.get(zh_ids[0], "") if zh_ids else ""
        tokens = tokenize_sentence(english_text)
        if not tokens:
            continue

        matched_counts: Counter[str] = Counter()
        token_counts = Counter(tokens)
        for token in set(tokens):
            for content in single_targets.get(token, []):
                matched_counts[content] += token_counts[token]

        max_len = min(max_phrase_len, len(tokens), 8)
        for size in range(2, max_len + 1):
            for start in range(0, len(tokens) - size + 1):
                ngram = tuple(tokens[start : start + size])
                for content in phrase_targets.get(ngram, []):
                    matched_counts[content] += 1

        for content, match_count in matched_counts.items():
            if english_text in seen_english[content]:
                stats["duplicate_sentence"] += 1
                continue
            candidates[content].append(
                ExampleCandidate(en=english_text, zh=zh_text, sentence_id=sentence_id, match_count=match_count)
            )
            seen_english[content].add(english_text)

    ranked: dict[str, list[ExampleCandidate]] = {}
    for content, examples in candidates.items():
        examples.sort(key=lambda example: (0 if example.zh else 1, len(example.en), example.match_count, example.en))
        ranked[content] = examples[:max_examples]
    return ranked, stats


def build_examples_json(examples: Iterable[ExampleCandidate], max_chars: int = 4096) -> str:
    json_text, _ = fit_examples_json(examples, max_chars=max_chars)
    return json_text


def fit_examples_json(examples: Iterable[ExampleCandidate], max_chars: int = 4096) -> tuple[str, int]:
    payload = [_example_to_json_object(example) for example in examples]
    original_count = len(payload)
    while payload:
        json_text = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
        if len(json_text) <= max_chars:
            return json_text, original_count - len(payload)
        payload.pop()
    return "[]", original_count


def _example_to_json_object(example: ExampleCandidate) -> dict[str, str]:
    return {"en": clean_sentence_text(example.en), "zh": clean_sentence_text(example.zh)}


def sql_quote(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def generate_update_sql(item_code: str, examples: Iterable[ExampleCandidate]) -> str:
    json_text = build_examples_json(examples)
    return f"UPDATE learning_item SET examples = {sql_quote(json_text)} WHERE item_code = {sql_quote(item_code)};"


def next_flyway_version(migration_dir: Path, start_version: int | None = None, file_count: int = 1) -> int:
    versions = {
        version
        for path in migration_dir.glob("V*__*.sql")
        for version in [_parse_flyway_version(path.name)]
        if version is not None
    }
    if start_version is None:
        return (max(versions) if versions else 0) + 1
    collisions = [version for version in range(start_version, start_version + file_count) if version in versions]
    if collisions:
        raise ValueError(f"generated Flyway version(s) collide with existing migrations: {collisions}")
    return start_version


def validate_generated_sql(path: Path) -> ValidationResult:
    paths = [path]
    if path.is_dir():
        paths = sorted(path.glob(GENERATED_GLOB), key=_flyway_sort_key)

    result = ValidationResult(files=len(paths))
    for sql_path in paths:
        sql_text = sql_path.read_text(encoding="utf-8")
        for statement in _split_sql_statements(sql_text):
            update_at = statement.lower().find("update learning_item set examples")
            if update_at == -1:
                continue
            statement = statement[update_at:]
            json_text, item_code = _parse_generated_update(statement)
            examples = json.loads(json_text)
            if not isinstance(examples, list):
                raise ValueError(f"{sql_path}: examples for {item_code} is not a JSON list")
            if len(json_text) > 4096:
                raise ValueError(f"{sql_path}: examples for {item_code} exceeds 4096 characters")
            for example in examples:
                if set(example) != {"en", "zh"} or not isinstance(example["en"], str) or not isinstance(example["zh"], str):
                    raise ValueError(f"{sql_path}: invalid example shape for {item_code}")
            result.update_statements += 1
            result.json_examples += len(examples)
    return result


def _split_sql_statements(sql_text: str) -> Iterator[str]:
    start = 0
    in_string = False
    i = 0
    while i < len(sql_text):
        char = sql_text[i]
        if in_string:
            if char == "'":
                if i + 1 < len(sql_text) and sql_text[i + 1] == "'":
                    i += 2
                    continue
                in_string = False
        elif char == "'":
            in_string = True
        elif char == ";":
            yield sql_text[start : i + 1].strip()
            start = i + 1
        i += 1


def _parse_generated_update(statement: str) -> tuple[str, str]:
    examples_marker = "examples ="
    where_marker = "WHERE item_code ="
    examples_at = statement.find(examples_marker)
    where_at = statement.find(where_marker)
    if examples_at == -1 or where_at == -1:
        raise ValueError(f"not a generated update statement: {statement[:120]}")
    json_text, json_end = _parse_sql_string_at(statement, statement.find("'", examples_at))
    item_code, _ = _parse_sql_string_at(statement, statement.find("'", where_at))
    if json_end > where_at:
        raise ValueError("malformed generated update statement")
    return json_text, item_code


def _parse_sql_string_at(text: str, start: int) -> tuple[str, int]:
    if start < 0 or text[start] != "'":
        raise ValueError("expected SQL string literal")
    i = start + 1
    chars: list[str] = []
    while i < len(text):
        char = text[i]
        if char == "'":
            if i + 1 < len(text) and text[i + 1] == "'":
                chars.append("'")
                i += 2
                continue
            return "".join(chars), i + 1
        chars.append(char)
        i += 1
    raise ValueError("unterminated SQL string literal")


def write_migration_files(
    migration_dir: Path,
    updates: list[tuple[str, list[ExampleCandidate]]],
    start_version: int | None = None,
    updates_per_file: int = 5000,
) -> list[Path]:
    if updates_per_file <= 0:
        raise ValueError("updates_per_file must be positive")
    file_count = (len(updates) + updates_per_file - 1) // updates_per_file
    first_version = next_flyway_version(migration_dir, start_version=start_version, file_count=file_count)
    written: list[Path] = []
    for part_number, offset in enumerate(range(0, len(updates), updates_per_file), start=1):
        version = first_version + part_number - 1
        path = migration_dir / f"V{version}__enrich_examples_with_tatoeba_part{part_number}.sql"
        lines = [GENERATED_HEADER]
        for item_code, examples in updates[offset : offset + updates_per_file]:
            lines.append(generate_update_sql(item_code, examples) + "\n")
        path.write_text("".join(lines), encoding="utf-8")
        written.append(path)
    return written


def build_updates(content_to_codes: dict[str, list[str]], matches: dict[str, list[ExampleCandidate]]) -> UpdatePlan:
    update_plan = UpdatePlan()
    for content in sorted(matches):
        examples = matches[content]
        if not examples:
            continue
        json_text, dropped = fit_examples_json(examples)
        final_count = len(json.loads(json_text))
        if final_count == 0:
            continue
        trimmed_examples = examples[:final_count]
        for item_code in content_to_codes.get(content, []):
            update_plan.updates.append((item_code, trimmed_examples))
            update_plan.json_examples += final_count
            update_plan.skipped_json_length += dropped
    update_plan.updates.sort(key=lambda item: item[0])
    return update_plan


def _flyway_sort_key(path: Path) -> tuple[int, str]:
    version = _parse_flyway_version(path.name)
    return (version if version is not None else 0, path.name)


def _parse_flyway_version(name: str) -> int | None:
    match = re.match(r"V(\d+)__", name)
    return int(match.group(1)) if match else None


def run_generation(args: argparse.Namespace) -> int:
    progress = Progress(enabled=not args.quiet)
    migration_dir = Path(args.migration_dir)
    if args.validate_only:
        result = validate_generated_sql(migration_dir)
        print(
            f"Validation PASS: files={result.files}, updates={result.update_statements}, json_examples={result.json_examples}"
        )
        return 0

    tatoeba_dir = Path(args.tatoeba_dir)
    progress.report("loading learning items from seed migrations", force=True)
    content_to_codes = load_learning_items(migration_dir)
    item_code_count = sum(len(codes) for codes in content_to_codes.values())
    progress.report(
        f"loaded {item_code_count:,} learning item codes across {len(content_to_codes):,} normalized content keys",
        force=True,
    )

    index = build_tatoeba_index(
        tatoeba_dir,
        min_sentence_len=args.min_sentence_len,
        max_sentence_len=args.max_sentence_len,
        progress=progress,
    )
    matches, skipped = match_examples(
        content_to_codes,
        index,
        max_examples=args.max_examples,
        allow_missing_zh=args.allow_missing_zh,
        progress=progress,
    )
    update_plan = build_updates(content_to_codes, matches)
    updates = update_plan.updates
    file_count = (len(updates) + args.updates_per_file - 1) // args.updates_per_file if updates else 0
    first_version = next_flyway_version(migration_dir, start_version=args.start_version, file_count=max(file_count, 1))
    version_range = f"V{first_version}..V{first_version + file_count - 1}" if file_count else "none"

    print(f"parsed_learning_item_codes={item_code_count}")
    print(f"unique_content_keys={len(content_to_codes)}")
    print(f"english_sentences_retained={index.stats.english_retained}")
    print(f"chinese_sentences_retained={index.stats.chinese_retained}")
    print(f"english_sentences_with_chinese_translations={index.stats.english_with_zh}")
    print(f"item_codes_with_examples={len(updates)}")
    print(f"content_keys_with_examples={len(matches)}")
    print(f"json_examples={update_plan.json_examples}")
    print(f"generated_flyway_version_range={version_range}")
    print(f"skipped_no_translation={skipped['no_translation']}")
    print(f"skipped_quality_filter={index.stats.skipped_quality_filter}")
    print(f"skipped_template_phrase={skipped['template_phrase']}")
    print(f"skipped_json_length={update_plan.skipped_json_length}")
    print(f"skipped_duplicate_sentence={skipped['duplicate_sentence']}")

    if args.dry_run:
        return 0
    if not updates:
        print("No updates generated", file=sys.stderr)
        return 1

    progress.report(f"writing {len(updates):,} UPDATE statements into {file_count:,} migration file(s)", force=True)
    paths = write_migration_files(
        migration_dir,
        updates,
        start_version=args.start_version,
        updates_per_file=args.updates_per_file,
    )
    for path in paths:
        result = validate_generated_sql(path)
        progress.report(
            f"validated {path.name}: updates={result.update_statements:,}, json_examples={result.json_examples:,}",
            force=True,
        )
    print("generated_files=" + ",".join(path.name for path in paths))
    return 0


def build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--tatoeba-dir", default="tatoeba")
    parser.add_argument("--migration-dir", default="java-core/src/main/resources/db/migration")
    parser.add_argument("--start-version", type=int)
    parser.add_argument("--updates-per-file", type=int, default=5000)
    parser.add_argument("--max-examples", type=int, default=3)
    parser.add_argument("--max-sentence-len", type=int, default=120)
    parser.add_argument("--min-sentence-len", type=int, default=12)
    parser.add_argument("--allow-missing-zh", action="store_true")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--validate-only", action="store_true")
    parser.add_argument("--quiet", action="store_true")
    return parser


def main(argv: list[str] | None = None) -> int:
    return run_generation(build_arg_parser().parse_args(argv))


if __name__ == "__main__":
    raise SystemExit(main())
